---
name: Tests

on:
  push:

  pull_request:
    branches:
      - master

jobs:
  astyle:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get install -y astyle

      - name: Artistic Style
        run: ./tests/lint/astyle.sh $(git ls-files '*.[ch]' | grep -v openssl_hostname_validation)

      - name: Linux Kernel Coding Style
        run: ./tests/lint/checkpatch.sh $(git ls-files '*.[ch]' | grep -v openssl_hostname_validation)

      - name: EOL at EOF
        run: ./tests/lint/eol-at-eof.sh $(git ls-files | grep -v openssl_hostname_validation)

      - name: Line Length
        run: ./tests/lint/line_length.py $(git ls-files '*.[ch]' | grep -v openssl_hostname_validation)

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: ./tests/ci/install_openssl.sh $HOME/.openfortivpn-deps

      - name: Build jwtb
        run: |
          ./autogen.sh
          export PKG_CONFIG_PATH="$HOME/.openfortivpn-deps/lib/pkgconfig"
          echo "jwtb - before configure"
          echo `pwd`
          ./configure --prefix=/usr --sysconfdir=/etc
          echo "jwtb - before make"
          make
          ls -altr *
