---
name: Tests

on:
  push:

  pull_request:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    
        
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: jwtb dir
        run: |
          mkdir jwtb   
          echo 'alpha' > alpha.txt        

      - name: Install Dependencies
        run: ./tests/ci/install_openssl.sh $HOME/.openfortivpn-deps

      - name: Build jwtb
        run: |
          ./autogen.sh
          export PKG_CONFIG_PATH="$HOME/.openfortivpn-deps/lib/pkgconfig"
          echo "jwtb - before configure"
          ./configure --prefix=/usr --sysconfdir=/etc
          echo "jwtb - before make"
          make
          ls -altr 
          echo "^^^^^"
          ls -altrR *
          tar --exclude='./jwtb' -cvf jwtb/dir.tar .

          
      - name: jwtb - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: jwtb         